name: Run Tests

on:
 - push
 - workflow_dispatch
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true
        
    - name: NPM Install
      run: npm install

    - name: Run Tests
      run: npm run test
