# Automatically fetches the latest API spec (and commits the submodule update) and generates a new client
name: Generate Client

on:
 - push
 - workflow_dispatch
jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true

    - name: Run Type Checker
      run: npm run test:ts
